### ISSUE TITLE
delete component if removed from config

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/rudr#134]
let me give an example about this issue:

first，I apply a Configuration, something like this:

```
apiVersion: core.hydra.io/v1alpha1
kind: OperationalConfiguration
metadata:
  name: first-app
spec:
  components:
  - name: component-A
    instanceName: app1
    parameterValues:
      - name: poet
        value: Eliot
  - name: component-B
    instanceName: app-2
    parameterValues:
      - name: poet
        value: Eliot
```

then, I hope to modify my configuration to:

```
apiVersion: core.hydra.io/v1alpha1
kind: OperationalConfiguration
metadata:
  name: first-app
spec:
  components:
  - name: component-C
    instanceName: app3
    parameterValues:
      - name: poet
        value: Eliot
  - name: component-B
    instanceName: app-2
    parameterValues:
      - name: poet
        value: Eliot
```

this means , I don't need component-A  anymore, and I want to add component-C.
So, in our framework, we don't have the power to delete component-A from modified config.

And this could be done by supporting component version recorded(https://github.com/microsoft/scylla/pull/131) and component delete(#132 )
