### ISSUE TITLE
Undesired node selector inserted

### ISSUE THREAD

**Issue by jiria** [oam-dev/rudr#189]
I have created a new component with application configuration and the following node selector was added into the generated pod (without being requested in the component yaml):
```
Node-Selectors:  kubernetes.io/arch=amd64
```
Note that I was trying to deploy to ARM64 box. 

Here is the corresponding component:
```
apiVersion: core.hydra.io/v1alpha1
kind: ComponentSchematic
metadata:
  name: monitoring-replicated
spec:
  workloadType: core.hydra.io/v1alpha1.ReplicatedService
  os: linux
  containers:
  - name: monitoring
    image: foo
    ports:
    - name: sink
      containerPort: 80
      protocol: TCP
```

Interestingly enough, the same node selector was not added onto my Worker component.
