### ISSUE TITLE
Proposal: add K8s resource status to ApplicationConfiguration status

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/rudr#231]
Now our ApplicationConfiguration have status like below:

```
apiVersion: core.hydra.io/v1alpha1
kind: ApplicationConfiguration
metadata:
...
spec:
  components:
  - instanceName: first-app-nginx
    name: nginx-component
    parameterValues:
      ...
    traits:
    - name: ingress
      parameterValues:
       ...
status:
  phase: Add
```

We suggest add K8s resource status in it like below:

```
apiVersion: core.hydra.io/v1alpha1
kind: ApplicationConfiguration
metadata:
...
spec:
  components:
  - instanceName: first-app-nginx
    name: nginx-component
    parameterValues:
      ...
    traits:
    - name: ingress
      parameterValues:
       ...
status:
  phase: Add
  components:
      first-app:
           pod/first-app-nginx: Running
           service/first-app-nginx: Created
           ingress/first-app-nginx-trait-ingress: Created  
```

With this kind of status, we could have these benefits:

1. K8s user will more easy to understand how Scylla is working, how an AppConfig is converted to K8s resources will very clear.
2. In Scylla, they are K8s resources who real influence whether the app is working correctly, indicate the K8s resources status in AppConfig Object Status is reasonable.
3. When we update AppConfig, It will be more easier to diff and find what K8s resources are deleted or created. We now have this diff feature for components in AppConfig, but when a component has multiple traits, we can't find whether there are traits deleted.

Thanks to @resouer and @hongchaodeng , they give me this idea.

I'll try to implement in  https://github.com/microsoft/scylla/pull/177.

What do you think?  @technosophos @fibonacci1729 @suhuruli
