### ISSUE TITLE
implement traits diff and deleted traits removed from AppConfig when component updated

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/rudr#236]
As I mentioned in #231, we don't implement traits diff and deleted traits which were removed from AppConfig.

For exampe:

I installed an app like below:

```
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: first-app
spec:
  components:
    - componentName: helloworld-python-v1
      instanceName: first-app-helloworld-python-v1
      traits:
        - name: autoscaler
          parameterValues:
            - name: maximum
              value: 6
            - name: minimum
              value: 2
            - name: cpu
              value: 50
        - name: ingress
          parameterValues:
            - name: hostname
              value: example.com
            - name: service_port
              value: 9999
```

After several days, I update the appConfig and remove the autoscaler trait and add a manual-scaler trait:

```
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: first-app
spec:
  components:
    - componentName: helloworld-python-v1
      instanceName: first-app-helloworld-python-v1
      traits:
        - name: manual-scaler
          parameterValues:
            - name: replicaCount
              value: 3
        - name: ingress
          parameterValues:
            - name: hostname
              value: example.com
            - name: service_port
              value: 9999
```

In this case, we should find the difference between two AppConfig and delete the autoscaler trait which is hpa instance of K8s in rudr.
