### ISSUE TITLE
Pods Unable to Deploy to Azure Kubernetes Service (AKS) Due to "beta" Labels

### ISSUE THREAD

**Issue by AaronCrawfis** [oam-dev/rudr#237]
When I attempt to apply a configuration to aks I get the error:

Component:
```yaml
apiVersion: core.hydra.io/v1alpha1
kind: ComponentSchematic
metadata:
  name: helloworld-frontend
  version: "1.0.0"
  description: Front-end web server demonstrating Hydra capabilities
spec:
  workloadType: core.hydra.io/v1alpha1.ReplicatedService
  os: linux
  arch: amd64
  parameters:
    - name: oam_message
      type: string
      required: true
      default: Default value from spec
  containers:
    - name: server
      image: XXX
      env:
        - name: OAM_MESSAGE
          value: Default value from component
          fromParam: oam_message
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
```
Configuration:
```yaml
# This operations configuration describes the oam-helloworld app
apiVersion: core.hydra.io/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: oam-helloworld
spec:
  components:
    - name: helloworld-frontend
      instanceName: hw-fe
      parameterValues:
        - name: oam_message
          value: Hello from AKS
      traits:
        - name: ingress
          parameterValues:
            - name: hostname
              value: aks.azureocto.com
            - name: path
              value: /
            - name: service_port
              value: 80
```

```
$ kubectl get events
LAST SEEN     TYPE           REASON                KIND      MESSAGE
17s           Warning        FailedScheduling      Pod      0/1 nodes are available: 1 node(s) didn't match node selector
```

As a workaround I run `kubectl edit node <aks-node>` and remove "beta" from the os and arch labels. Then the pod deploys and runs correctly.
