### ISSUE TITLE
Question: Port Mapping in Scylla

### ISSUE THREAD

**Issue by suhuruli** [oam-dev/rudr#290]
I was trying a sample with the following scenario: 

- VueJS app listening on port 8080
- In the component YAML, the containerPort is set to 8080 
- In the `ingress` trait, I set the service_port to 80 because that's what the NGINX controller is listening on externally for 

Expected result: If I hit the public endpoint with appropriate path and hostname, I should be able to reach my VueJS server. 

Actual result: 

- Scylla creates a service for my component with port: 8080 and targetPort: 8080 
- Scylla creates an Ingress with the following spec. However, the service is not listening on port 80 but 8080. I resolved this by doing a `k edit ingress` and changing the servicePort below to 8080. 

Is there another way to do this because from a user experience perspective, I think this shouldn't be necessary.  

```yaml 
spec:
  rules:
  - host: servicetracker.hydra.com
    http:
      paths:
      - backend:
          serviceName: service-tracker-ui
          servicePort: 80
        path: /
```
