### ISSUE TITLE
Add support for Dapr applications

### ISSUE THREAD

**Issue by amolenk** [oam-dev/rudr#398]
Dapr applications use deployment annotations such as `dapr.io/enabled: true` to let the Dapr control plane inject a sidecar in the deployment. Is it currently possible with OAM/Rudr to define such annotations in the ComponentSchematic/ApplicationConfiguration?

**Comment by hongchaodeng** [comment]
Yes. There is no reason why  Dapr applications can't be defined in OAM.

IMHO, Dapr runtime should be modelled as a _Workload_ type. It's tightly coupled to application logic and developers need to choose and tweak it in their Components.

**Comment by suhuruli** [comment]
I agree with @hongchaodeng. Having dapr as a Workload Type makes most sense to me as well. This would be a fantastic enhancement to have. 

@msfussell

**Comment by technosophos** [comment]
Such annotations can be defined on the ComponentSchematic, and they are automatically passed down to the resulting pods. 

https://github.com/oam-dev/rudr/blob/master/src/workload_type/server.rs#L75

https://github.com/oam-dev/rudr/blob/master/src/workload_type/workload_builder.rs#L209

Is there something else you believe is necessary? IIRC, we already tested this with Dapr and it worked fine.

**Comment by amolenk** [comment]
@technosophos You're absolutely right, I missed the annotations on the component.

This works fine:

```
apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: sort-service
  annotations:
    dapr.io/enabled: "true"
    dapr.io/id: "sortservice"
    dapr.io/port: "3000"
spec:
  workloadType: core.oam.dev/v1alpha1.Server
  containers:
    - name: sort-service
      image: amolenk/airport-mesh:sort-1.0
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
```
