### ISSUE TITLE
Autoscaling workloads with KEDA

### ISSUE THREAD

**Issue by tomkerkhove** [oam-dev/rudr#518]
**OAM Spec Info**

Rudr will always follow OAM spec, if this feature is related with spec definition, please make sure they are consistent.

**Is your feature request related to a problem? Please describe.**
I'd like to scale workloads on other metrics than CPU/Memory with the Autoscaler trait.

**Describe the solution you'd like**
Autoscale based on Service Bus queue size

**Additional context**
I'm translating my KEDA sample (https://github.com/kedacore/sample-dotnet-worker-servicebus-queue) to OAM to give an example of what OAM leverages.

KEDA is already mentioned in the Autoscaler trait but doesn't seem to be supported, is that correct?

https://github.com/oam-dev/rudr/blob/master/docs/concepts/traits.md#autoscaler-trait

**Scenario**
```yaml
apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: order-worker-component
spec:
  workloadType: core.oam.dev/v1alpha1.Server
  containers:
    - name: order-worker-container
      image: tomkerkhove/keda-sample-dotnet-worker-servicebus-queue
      env:
        - name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
          fromParam: ServiceBus_Queue_Connectionstring
        - name: PORT
          fromParam: port
      ports:
        - protocol: TCP
          containerPort: 9999
          name: http
  parameters:
    - name: ServiceBus_Queue_Connectionstring
      description: 'Connection string for the Azure Service Bus queue'
      type: string
      required: true
---
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: order-worker-config
spec:
  components:
    - componentName: order-worker-component
      instanceName: order-worker-component
      parameterValues:
        - name: ServiceBus_Queue_Connectionstring
          value: "<redacted>"
      traits:
        - name: auto-scaler.core.oam.dev/v1alpha1
          properties:
            maximum: 5
            minimim: 0
```
