### ISSUE TITLE
Ingress trait not creating the hostname : rudr 0.1.0

### ISSUE THREAD

**Issue by sowsan** [oam-dev/rudr#519]
**rudr version:** 0.1.0

**helm version:**
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

**Output of kubectl version:**
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"524c3a1238422529d62f8e49506df658fa9c8b8c", GitTreeState:"clean", BuildDate:"2019-11-14T05:26:24Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):**
AKS and GKE

An application installed with a trait for ingress is not creating with the assigned hostname.

Using the Nginx Ingress Controller, everything was working fine till last week.

Tried with both samples listed here : https://github.com/oam-dev/samples

**Comment by resouer** [comment]
ref: https://github.com/oam-dev/rudr/pull/516

**Comment by hongchaodeng** [comment]
Hi @sowsan 

Thanks for reporting the issue. I apologized for the delay in replying.

The sample's traits are outdated. Since #516 , all the traits have been changed to _object_ style mapping.

Here's a comparison:

```yaml
# old
    traits:
      - name: ingress
        parameterValues:
          - name: hostname
            value: servicetracker.oam.io
          - name: path
            value: / 
          - name: service_port
            value: 8080     
---
# new
      traits:
        - name: ingress
          properties:
            hostname: example.com
            path: /
            servicePort: 9999
```

Would you update the samples?
